# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

We want to help R developers to leverage serverless computing for training and scoring R models. We want to build a plattform independent framework that allows R developers to deploy their solution to different cloud providers with a consistent, unified API.

We want to build a framework similar to serverless.com but specifically targeted to R users.

R developers should be able to:

- deploy arbitrary R code using an arbitary R runtime
- using a consistent API for different cloud providers

We want to build a CLI to provision:
- Serverless batch jobs
- Serverless functions


## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

To keep the scope of the project manageable and because most of our experience is with Microsoft Azure, we plan to build the following Minimum Viable Product:

- Extent the rAzure package to setup serverless batch clusters using R based Docker images
- Build an R-language worker to run on Azure Functions or alternatively on Azure Container Instances

The rAzure package already allows specification of compute pools, jobs and tasks and we want to extent its functionality to include setting up compute schedules for recurring batch jobs.

The main part of our work will focus on developing an R-language worker for Azure functions.

Azure functions runtime version 2 supports Docker images and therefore arbitrary language workers as long as they implement gRPC to talk to the host process.


From Azure website:
> For gRPC, we currently have one call which creates a duplex stream of StreamingMessages, which are the protobuf messages defined below. All messages between host and worker flow across this bi-directional stream. The host runs the gRPC server, and the language worker processes act as clients.

- Functions: 
Azure Functions: https://azure.microsoft.com/en-us/blog/introducing-azure-functions-2-0/
Azure Functions Linux consumption plan: https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-on-Linux-Preview
Cross platform hosting: https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-Runtime-2.0-Overview

AWS Lambda : https://github.com/grycap/scar

Serverless R - Framework for Azure/Fn/OpenWhisk/Kubernetes (anything with Docker support really). RStudio-CLI for deploying R-serverless-jobs. 



