# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

We do believe that the mentioned project team should be enough to succesfully finish the project. We are in contact with Microsoft's product team responsible for Azure Batch and Azure Functions.


## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

We will setup a Github repository with a project page where we track all work items on Github's kanban board. We will also setup a Slack channel for the development team and further potential contributors. We plan to setup a CI pipeline for automated testing as well.


## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

Azure Functions v2 can be run in Docker containers and are therefore platform independent. Development and deployment can be done both locally or with a cloud provider of our choice. Since we are most comfortable working with Azure, we will leverage Azure's infrastructure.

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

Our suggested funding requirements are:

- USD 10,000 for 200 work-hours

At a rate of EUR 50 per hour, this would translate to 200 hours for three developers and would also be used to cover development costs for cloud resources if necessary.


## Summary
<!--
A summary of the requirements that contextualises the costs
-->

Providing a serverless framework for R would enable data scientists to easily deploy models to production without having to bother with setting up infrastructure, patching systems and so forth.

